/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

//Definiendo nuevas variables

unsigned char edificios = 0;
unsigned char counter_i = 0;
unsigned char number_of_students = 0;


/* Función principal del programa: cuando programamos en C cada sentencia que escribimos
 * debe estar dentro de una función, en este momento la única función que tenemos es
 * el main, entonces todas las sentencias que escribamos deben estar dentro de una
 * función. Las sentencias son cualquier operación, puede ser una asignación también. */
int main(void)
{
	edificios = 10;
	counter_i = 32;
	number_of_students = 20;

	edificios = edificios + counter_i;

    /* Loop forever */
	while(1) {
		;
	}
}
